name: repeatandlearn
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Gerenciador de estados
  flutter_riverpod: ^2.3.6
  # Rotas
  go_router: ^7.0.1
  # Back4app
  parse_server_sdk_flutter: ^5.0.1
  # outros
  validatorless: ^1.2.3
  intl: ^0.17.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
